server:
  port: 8080
  servlet:
    contextPath: /
  undertow:
    io-threads: 20          # default value is 1 thread per CPU core
    worker-threads: 100     # default value is 8 threads per CPU core
    max-http-post-size: 2097152     # 2M as weblogic default value


spring:
  datasource:
    url: jdbc:mysql://localhost/for_one?serverTimezone=UTC
    username: fund
    password: fund@forOne
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  http:
    converters:
      preferred-json-mapper: gson


# show the sql variable in log
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: trace
